/*
    Allow RETIRED status on gearbox assets.
*/

USE SFC_WR_DB;
GO

IF EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = N'CK_TB_CM_GEARBOX_STATUS'
      AND parent_object_id = OBJECT_ID(N'dbo.TB_CM_GEARBOX_ASSET')
)
BEGIN
    ALTER TABLE dbo.TB_CM_GEARBOX_ASSET DROP CONSTRAINT CK_TB_CM_GEARBOX_STATUS;
END;
GO

ALTER TABLE dbo.TB_CM_GEARBOX_ASSET
    ADD CONSTRAINT CK_TB_CM_GEARBOX_STATUS
    CHECK (STATUS IN ('SPARE', 'IN_USE', 'REPAIR', 'RETIRED'));
GO
