/*
    Add process/line scope to component tracker.
    Existing rows → STRANDING / BUNCHER (current Buncher board).
*/

USE SFC_WR_DB;
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF COL_LENGTH('dbo.TB_COMPONENTS_TRACKER', 'PROCESS_CD') IS NULL
BEGIN
    ALTER TABLE dbo.TB_COMPONENTS_TRACKER ADD PROCESS_CD VARCHAR(20) NULL;
END;
GO

IF COL_LENGTH('dbo.TB_COMPONENTS_TRACKER', 'LINE_CD') IS NULL
BEGIN
    ALTER TABLE dbo.TB_COMPONENTS_TRACKER ADD LINE_CD VARCHAR(20) NULL;
END;
GO

UPDATE dbo.TB_COMPONENTS_TRACKER
SET PROCESS_CD = 'STRANDING',
    LINE_CD = 'BUNCHER'
WHERE PROCESS_CD IS NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_TB_COMPONENTS_TRACKER_PROCESS'
      AND object_id = OBJECT_ID(N'dbo.TB_COMPONENTS_TRACKER')
)
BEGIN
    CREATE INDEX IX_TB_COMPONENTS_TRACKER_PROCESS
        ON dbo.TB_COMPONENTS_TRACKER (PROCESS_CD, LINE_CD, [USE])
        INCLUDE (MACHINE_NM, PART_TYPE, PART_ID);
END;
GO
