/*
    Free-text component names + optional details shown on click.

    - Widen PART_TYPE (was VARCHAR(10)) — drop/recreate dependent index
    - Add PART_DETAILS

    Run with sqlcmd -I (QUOTED_IDENTIFIER ON).
*/

USE SFC_WR_DB;
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF COL_LENGTH(N'dbo.TB_COMPONENTS_TRACKER', N'PART_DETAILS') IS NULL
BEGIN
    ALTER TABLE dbo.TB_COMPONENTS_TRACKER
        ADD PART_DETAILS NVARCHAR(500) NULL;
END;
GO

IF EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_TB_COMPONENTS_TRACKER_PROCESS'
      AND object_id = OBJECT_ID(N'dbo.TB_COMPONENTS_TRACKER')
)
BEGIN
    DROP INDEX IX_TB_COMPONENTS_TRACKER_PROCESS ON dbo.TB_COMPONENTS_TRACKER;
END;
GO

ALTER TABLE dbo.TB_COMPONENTS_TRACKER
    ALTER COLUMN PART_TYPE NVARCHAR(100) NOT NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_TB_COMPONENTS_TRACKER_PROCESS'
      AND object_id = OBJECT_ID(N'dbo.TB_COMPONENTS_TRACKER')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_TB_COMPONENTS_TRACKER_PROCESS
        ON dbo.TB_COMPONENTS_TRACKER (PROCESS_CD, LINE_CD, [USE])
        INCLUDE (MACHINE_NM, PART_TYPE, PART_ID);
END;
GO
