/*
    Add friendly display name for gearbox assets.
*/

USE SFC_WR_DB;
GO

IF COL_LENGTH('dbo.TB_CM_GEARBOX_ASSET', 'GEARBOX_NM') IS NULL
BEGIN
    ALTER TABLE dbo.TB_CM_GEARBOX_ASSET
        ADD GEARBOX_NM NVARCHAR(100) NULL;
END;
GO

UPDATE dbo.TB_CM_GEARBOX_ASSET
SET GEARBOX_NM = CASE
        WHEN GEARBOX_NM IS NULL OR LTRIM(RTRIM(GEARBOX_NM)) = N''
            THEN N'Gearbox ' + RIGHT(GEARBOX_ID, 2)
        ELSE GEARBOX_NM
    END
WHERE GEARBOX_NM IS NULL OR LTRIM(RTRIM(GEARBOX_NM)) = N'';
GO
