/*
    Component monitoring — process / line machine registry.
    Users key in which machines belong to each process (and Stranding line).
*/

USE SFC_WR_DB;
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.TB_CM_MACHINE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_CM_MACHINE
    (
        COMPANY      VARCHAR(10)   NOT NULL,
        FACTORY      VARCHAR(20)   NOT NULL,
        PROCESS_CD   VARCHAR(20)   NOT NULL,  -- INLINE / DRAWING / STRANDING / CLOSING / REWINDER
        LINE_CD      VARCHAR(20)   NULL,      -- BUNCHER / TUBULAR (Stranding); NULL otherwise
        MACHINE_NM   NVARCHAR(100) NOT NULL,
        MACHINE_CD   NVARCHAR(50)  NULL,      -- INLINE: user-entered code; NULL = not linked
        USE_YN       CHAR(1)       NOT NULL CONSTRAINT DF_TB_CM_MACHINE_USE DEFAULT ('Y'),
        CREATED_DT   DATETIME      NOT NULL CONSTRAINT DF_TB_CM_MACHINE_CREATED DEFAULT (GETDATE()),
        LAST_CHG_DT  DATETIME      NULL,
        CONSTRAINT PK_TB_CM_MACHINE PRIMARY KEY (COMPANY, FACTORY, PROCESS_CD, MACHINE_NM),
        CONSTRAINT CK_TB_CM_MACHINE_USE CHECK (USE_YN IN ('Y', 'N'))
    );

    CREATE INDEX IX_TB_CM_MACHINE_PROCESS
        ON dbo.TB_CM_MACHINE (PROCESS_CD, LINE_CD, USE_YN)
        INCLUDE (MACHINE_NM);
END;
GO
