/*
    SFC_WR_DB — gearbox & skipper (SF / SB)

    PART_SEQ per machine (via MACHINE_NM):
      1 = Gearbox   (PART_TYPE GEARBOX)
      2 = Skipper SF (PART_TYPE SF)
      3 = Skipper SB (PART_TYPE SB)

    PART_ID example: FP202601001
*/

USE SFC_WR_DB;
GO

IF OBJECT_ID(N'dbo.TB_COMPONENTS_TRACKER', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_COMPONENTS_TRACKER
    (
        COMPANY             VARCHAR(10)     NOT NULL,
        FACTORY             VARCHAR(20)     NOT NULL,
        PART_ID             VARCHAR(20)     NOT NULL,
        PART_SEQ            INT             NOT NULL,
        PART_TYPE           VARCHAR(20)     NOT NULL,
        MACHINE_NM          NVARCHAR(100)   NOT NULL,
        REPLACE_DT          DATETIME        NOT NULL,
        DISMANTLE_DT        DATETIME        NULL,
        RUNTIME_LIMIT_HOUR  DECIMAL(12, 2)  NOT NULL,
        RUNTIME_SEC         BIGINT          NOT NULL
            CONSTRAINT DF_TB_COMPONENTS_TRACKER_RUNTIME_SEC DEFAULT (0),
        [USE]               CHAR(1)         NOT NULL
            CONSTRAINT DF_TB_COMPONENTS_TRACKER_USE DEFAULT ('Y'),

        CONSTRAINT PK_TB_COMPONENTS_TRACKER
            PRIMARY KEY CLUSTERED (PART_ID),

        CONSTRAINT CK_TB_COMPONENTS_TRACKER_SEQ
            CHECK (PART_SEQ IN (1, 2, 3)),

        CONSTRAINT CK_TB_COMPONENTS_TRACKER_USE
            CHECK ([USE] IN ('Y', 'N'))
    );

    CREATE NONCLUSTERED INDEX IX_TB_COMPONENTS_TRACKER_MACHINE
        ON dbo.TB_COMPONENTS_TRACKER (MACHINE_NM)
        INCLUDE (PART_SEQ, PART_TYPE, RUNTIME_SEC, RUNTIME_LIMIT_HOUR, REPLACE_DT, [USE]);

    CREATE NONCLUSTERED INDEX IX_TB_COMPONENTS_TRACKER_COMPANY_FACTORY
        ON dbo.TB_COMPONENTS_TRACKER (COMPANY, FACTORY);

    CREATE UNIQUE NONCLUSTERED INDEX UQ_TB_COMPONENTS_TRACKER_MACHINE_SEQ_ACTIVE
        ON dbo.TB_COMPONENTS_TRACKER (MACHINE_NM, PART_SEQ)
        WHERE [USE] = 'Y';
END;
GO

-- Initial data: run seed_tb_components_tracker.sql
