/*
    Gearbox asset pool + mount history (repair/rotate model).
*/

USE SFC_WR_DB;
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.TB_CM_GEARBOX_ASSET', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_CM_GEARBOX_ASSET
    (
        COMPANY              VARCHAR(10)   NOT NULL,
        FACTORY              VARCHAR(20)   NOT NULL,
        GEARBOX_ID           VARCHAR(20)   NOT NULL,
        GEARBOX_NM           NVARCHAR(100) NULL,
        PROCESS_CD           VARCHAR(20)   NOT NULL,
        LINE_CD              VARCHAR(20)   NULL,
        STATUS               VARCHAR(10)   NOT NULL,  -- SPARE / IN_USE / REPAIR
        CURRENT_MACHINE_NM   NVARCHAR(100) NULL,
        CURRENT_PART_ID      VARCHAR(20)   NULL,
        LIFETIME_RUNTIME_SEC BIGINT        NOT NULL CONSTRAINT DF_TB_CM_GEARBOX_LIFE DEFAULT (0),
        CREATED_DT           DATETIME      NOT NULL CONSTRAINT DF_TB_CM_GEARBOX_CREATED DEFAULT (GETDATE()),
        LAST_CHG_DT          DATETIME      NULL,
        CONSTRAINT PK_TB_CM_GEARBOX_ASSET PRIMARY KEY (COMPANY, FACTORY, GEARBOX_ID),
        CONSTRAINT CK_TB_CM_GEARBOX_STATUS CHECK (STATUS IN ('SPARE', 'IN_USE', 'REPAIR'))
    );

    CREATE INDEX IX_TB_CM_GEARBOX_POOL
        ON dbo.TB_CM_GEARBOX_ASSET (PROCESS_CD, LINE_CD, STATUS)
        INCLUDE (GEARBOX_ID, CURRENT_MACHINE_NM);
END;
GO

IF OBJECT_ID(N'dbo.TB_CM_GEARBOX_HISTORY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_CM_GEARBOX_HISTORY
    (
        HIST_ID       BIGINT IDENTITY(1, 1) NOT NULL,
        COMPANY       VARCHAR(10)   NOT NULL,
        FACTORY       VARCHAR(20)   NOT NULL,
        GEARBOX_ID    VARCHAR(20)   NOT NULL,
        MACHINE_NM    NVARCHAR(100) NOT NULL,
        PART_ID       VARCHAR(20)   NULL,
        PROCESS_CD    VARCHAR(20)   NOT NULL,
        LINE_CD       VARCHAR(20)   NULL,
        MOUNT_DT      DATETIME      NOT NULL,
        DISMOUNT_DT   DATETIME      NULL,
        RUNTIME_SEC   BIGINT        NOT NULL CONSTRAINT DF_TB_CM_GEARBOX_HIST_RT DEFAULT (0),
        REASON        VARCHAR(20)   NULL,
        CONSTRAINT PK_TB_CM_GEARBOX_HISTORY PRIMARY KEY (HIST_ID)
    );

    CREATE INDEX IX_TB_CM_GEARBOX_HIST_GB
        ON dbo.TB_CM_GEARBOX_HISTORY (GEARBOX_ID, MOUNT_DT DESC);
END;
GO
